version: '3'

services:
    backend_lab:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: "80"
        ports: 
        - "80:8080"
        